# Generated by Django 4.0.3 on 2022-05-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_PN', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('All types', 'All types'), ('Analyzer', 'Analyzer'), ('Board', 'Board'), ('Board with display', 'Board with display'), ('Development board', 'Development board'), ('Display Touch Panel', 'Display Touch Panel'), ('Elevator', 'Elevator'), ('Kit - Debug adapter', 'Kit - Debug adapter'), ('Lauterbach Body', 'Lauterbach Body'), ('Lauterbach Head', 'Lauterbach Head'), ('Measurement card', 'Measurement card'), ('PC', 'PC'), ('Power stage', 'Power stage')], max_length=50)),
                ('inventory_number', models.CharField(max_length=15)),
                ('team', models.CharField(choices=[('All teams', 'All teams'), ('MICR SW Operations and Quality', 'MICR SW Operations and Quality'), ('MICR SW Libs', 'MICR SW Libs'), ('AITEC', 'AITEC'), ('IMX ToolBox', 'IMX ToolBox'), ('IMCUXpresso Config Tools', 'IMCUXpresso Config Tools'), ('MPU Systems EMEA', 'MPU Systems EMEA'), ('MICR Solution Engineering', 'MICR Solution Engineering'), ('GPIS Solutions', 'GPIS Solutions'), ('MICR STEC', 'MICR STEC'), ('EP SW ATT', 'EP SW ATT'), ('Secure Provisioning SDK', 'Secure Provisioning SDK'), ('DevOps', 'DevOps'), ('Secure Provisioning SDK', 'Secure Provisioning SDK')], max_length=50)),
                ('full_count', models.PositiveIntegerField()),
                ('free_count', models.PositiveIntegerField()),
                ('location', models.CharField(choices=[('All locations', 'All locations'), ('Brno', 'Brno'), ('R-113 Cupboard', 'R-113 Cupboard'), ('R-114 Cupboard', 'R-114 Cupboard'), ('Roznov', 'Roznov')], max_length=50)),
                ('placement', models.CharField(max_length=50)),
            ],
        ),
    ]
