# Generated by Django 4.0.3 on 2022-05-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_borrowed_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='free_count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='full_count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='inventory_number',
        ),
    ]
